// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQzSjbJ1zxLS1Wfrz4qj06GOrAdbJGNus',
    appId: '1:633808042190:web:f51bb5a9c6ad75369cb89f',
    messagingSenderId: '633808042190',
    projectId: 'agrilink-by-rysera',
    authDomain: 'agrilink-by-rysera.firebaseapp.com',
    storageBucket: 'agrilink-by-rysera.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwQoGyGkeZiw67im7SqoGjxGcUBp1MWY',
    appId: '1:633808042190:android:0f79f8d1d07034a69cb89f',
    messagingSenderId: '633808042190',
    projectId: 'agrilink-by-rysera',
    storageBucket: 'agrilink-by-rysera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhC1oztoDJzlkJh-sV4SsIctZ9l_CPTg',
    appId: '1:633808042190:ios:71adfdfc26faae5f9cb89f',
    messagingSenderId: '633808042190',
    projectId: 'agrilink-by-rysera',
    storageBucket: 'agrilink-by-rysera.appspot.com',
    iosClientId: '633808042190-vro232afr3go03m914lm1h2ie32ju26j.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrilink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPhC1oztoDJzlkJh-sV4SsIctZ9l_CPTg',
    appId: '1:633808042190:ios:71adfdfc26faae5f9cb89f',
    messagingSenderId: '633808042190',
    projectId: 'agrilink-by-rysera',
    storageBucket: 'agrilink-by-rysera.appspot.com',
    iosClientId: '633808042190-vro232afr3go03m914lm1h2ie32ju26j.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrilink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQzSjbJ1zxLS1Wfrz4qj06GOrAdbJGNus',
    appId: '1:633808042190:web:4c6e810dee9681e39cb89f',
    messagingSenderId: '633808042190',
    projectId: 'agrilink-by-rysera',
    authDomain: 'agrilink-by-rysera.firebaseapp.com',
    storageBucket: 'agrilink-by-rysera.appspot.com',
  );
}
